version: '3.7'

services:
  api:
    restart: always
    build:
      context: .
      target: builder
    container_name: "ts-express-boilerplate"
    ports:
      - "3000:3000"
    expose:
      - "3000"
